version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'remembrall_user'
      MYSQL_PASSWORD: 'remembrall_pwd'
      MYSQL_DATABASE: "remembrall_dev"
    ports:
      - '3306:3306'
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:

